version: '3.1'

services:
  springboot:
    image: darshanreddymr/spring-boot-mongo:latest
    restart: always
    container_name: springboot
    ports:
      - 9091:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure   

  mongo:
    image: mongo
    container_name: spring-boot-mongo
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
    restart: always
    
volumes:
  data:
    #external: true
  data-bkp:
    #external: true
    
networks:
  default:
    external:
      name: springnetwork
